codecov:
  require_ci_to_pass: no
  notify:
    after_n_builds: 1
    wait_for_ci: no
    notify_error: true
component_management:
  individual_components:
    - component_id: src
      name: source code
    - component_id: tests
      name: tests
      paths:
        - .*/tests.rs$
        - .*/tests/**
coverage:
  status:
    project:
      default:
        target: auto
        informational: false
    patch:
      default:
        informational: false
