codecov:
  require_ci_to_pass: no
  notify:
    after_n_builds: 1
    wait_for_ci: no
    notify_error: true
coverage:
  status:
    project:
      default:
        target: auto
        informational: false
    patch:
      default:
        informational: false
