[workspace]
resolver = "3"
members = [
    "src",
    "src/memory",
    "src/memory/endianness",
    "src/memory/bitstream",
    "src/memory/bitvacuumer",
    "src/memory/bitstreamcache",
]

[workspace.package]
version = "0.1.0"
authors = ["Roman Lebedev <lebedev.ri@gmail.com>"]
edition = "2024"
rust-version = "1.87"  # MSRV:1
documentation = "https://rawspeed.rs"
homepage = "https://rawspeed.rs"
repository = "https://github.com/darktable-org/rawspeed.rs"
license = "MIT OR Apache-2.0"

[profile.release]
panic = 'abort'
