[package]
name = "rawspeed"
version = "0.1.0"
authors = ["Roman Lebedev <lebedev.ri@gmail.com>"]
year = "2025"
edition = "2024"
rust-version = "1.87"  # MSRV:1
documentation = "https://rawspeed.rs"
homepage = "https://rawspeed.rs"
repository = "https://github.com/darktable-org/rawspeed.rs"
license = "MIT OR Apache-2.0"

[dependencies]
