[package]
name = "rawspeed-memory-bytestreamer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-memory-endianness = { path = "../endianness" }
rawspeed-common = { path = "../../common" }

[lib]
path = "mod.rs"
