[package]
name = "rawspeed-utils-rstest"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-utils-librstest = { path = "../librstest" }

[[bin]]
name = "rstest"
path = "mod.rs"
