[package]
name = "rawspeed-bitstream-bitstream-decoder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-bitstream-bitstreamcache = { path = "../../bitstreamcache" }
rawspeed-bitstream-bitstreams = { path = "../../bitstreams" }
rawspeed-common = { path = "../../../common" }
rawspeed-memory-endianness = { path = "../../../memory/endianness" }
rawspeed-memory-fixed_length_load = { path = "../../../memory/fixed_length_load" }
rawspeed-memory-variable_length_load = { path = "../../../memory/variable_length_load" }

[lib]
path = "mod.rs"
